.TH "kernel.cu" 3 "Thu Nov 4 2021" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kernel.cu
.SH SYNOPSIS
.br
.PP
\fC#include 'image_handler\&.h'\fP
.br
\fC#include 'seam_carving\&.h'\fP
.br
\fC#include 'utils\&.cuh'\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <sys\\timeb\&.h>\fP
.br
\fC#include 'cuda_runtime\&.h'\fP
.br
\fC#include 'cuda_runtime_api\&.h'\fP
.br
\fC#include 'device_launch_parameters\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBapplySeamCarving\fP (char *p, int iterations)"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "char * \fBsrc_path\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void applySeamCarving (char * p, int iterations)"
Funzione principale Host che alloca la memoria necessaria all'algoritmo, legge l'immagine, lancia i vari step del seam carving e scrive la nuova immagine ottenuta\&. 
.PP
\fBParameters\fP
.RS 4
\fIp\fP Il path dell'immagine in input
.br
\fIiterations\fP Il numero di pixel orizzontali da rimuovere su ogni riga
.RE
.PP

.SS "int main (int argc, char ** argv)"

.SH "Variable Documentation"
.PP 
.SS "char* src_path"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
