.TH "C:/Users/tommi/OneDrive/Documenti/MEGAsync/Universita/Magistrale/Corsi/GPU Computing/Proj/SeamCarving/README.md" 3 "Thu Nov 4 2021" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/tommi/OneDrive/Documenti/MEGAsync/Universita/Magistrale/Corsi/GPU Computing/Proj/SeamCarving/README.md
.SH SYNOPSIS
.br
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
